exports.usuariosGafete = {
  PEVELASQUEZ: "28420",
  CTERCERO: "29275",
  ESERRANO: "25440",
  JAREYES: "25341",
  CCRAMIREZ: "27892",
  RVALLADARES: "29158",
  YNPEREZ: "30114",
  HESTRADA: "17292",
  LEFLORES: "23689",
  ALMARROQUINT: "26788",
  MFESTRADA: "26985",
  YMENDEZ: "27054",
  JAJCAN: "27557",
  DPALMA: "17357",
  WBAILON: "25488",
  SMOROZCOM: "28173",
  RCALITO: "17186",
  HASANCHEZ: "21128",
  WAVELASQUEZ: "23547",
  SCGONZALEZ: "24421",
  CTSANCHEZ: "25470",
  MAMADO: "26480",
  ROESCOBAR: "17291",
  JEORDONEZ: "31580",
  DGONZALEZ: "10626",
  SJMENA: "16004",
  RNAVASSI: "15802",
  DDEPAZM: "18918",
  MDVELASQUEZ: "28365",
  EQUICHE: "32601",
  RSRODRIGUEZ: "32832",
  OBERMUDEZ: "14443",
  EPORRAS: "15801",
  RRLOPEZ: "16560",
  WFLOPEZ: "18578",
  ECALVILLO: "21143",
  ABFRANCO: "21261",
  SANZOATEGUI: "28344",
  CHHERNANDEZ: "27066",
  JAMIRANDA: "31623"
};

exports.infoEmpleados = [
  { gafete: 28344, nombre: 'SIONIS GABRIELA ANZOÁTEGUI SALAZAR',          puesto: 'ANALISTA III',                              usuario: 'SANZOATEGUI' },
  { gafete: 28365, nombre: 'MARICARMEN DEL ROSARIO VELÁSQUEZ',            puesto: 'SECRETARIA EJECUTIVA I',                     usuario: 'MDVELASQUEZ' },
  { gafete: 32601, nombre: 'EDGAR ARNOLDO QUICHÉ CHIYAL',                 puesto: 'SUPERVISOR DE AUDITORÍA',                    usuario: 'EQUICHE' },
  { gafete: 32832, nombre: 'REYNA SUSANA RODRÍGUEZ CRUZ',                 puesto: 'OFICINISTA I',                               usuario: 'RSRODRIGUEZ' },
  { gafete: 14443, nombre: 'OLGA MARINA BERMÚDEZ ARANA',                  puesto: 'SECRETARIA V',                               usuario: 'OBERMUDEZ' },
  { gafete: 15801, nombre: 'ERICK GIOVANNI PORRAS RUBIO',                 puesto: 'SUPERVISOR GENERAL DE AUDITORÍA INTERNA',    usuario: 'EPORRAS' },
  { gafete: 16560, nombre: 'RÓMULO ROMILIO LÓPEZ SÁNCHEZ',                puesto: 'SUPERVISOR DE AUDITORÍA',                    usuario: 'RRLOPEZ' },
  { gafete: 18578, nombre: 'WILSON NICOLÁS LÓPEZ FLORIÁN',                puesto: 'SUPERVISOR DE AUDITORÍA',                    usuario: 'WFLOPEZ' },
  { gafete: 21143, nombre: 'ELISA AZUCENA CALVILLO VALDEZ',               puesto: 'AUXILIAR DE AUDITORÍA',                      usuario: 'ECALVILLO' },
  { gafete: 21261, nombre: 'ANDREA BEATRIZ FRANCO TRUJILLO',              puesto: 'ANALISTA III',                               usuario: 'ABFRANCO' },
  { gafete: 17357, nombre: 'DENNIS FERNANDO PALMA RAMÍREZ',               puesto: 'ANALISTA III',                               usuario: 'DPALMA' },
  { gafete: 25488, nombre: 'WILSON OTTONIEL BAILÓN LETONA',               puesto: 'ANALISTA III',                               usuario: 'WBAILON' },
  { gafete: 28173, nombre: 'SUSY MARÍA ELISA OROZCO MÉRIDA',              puesto: 'ANALISTA III',                               usuario: 'SMOROZCOM' },
  { gafete: 17186, nombre: 'REYNA LUZ CUEVAS CALITO',                     puesto: 'AUXILIAR OPERATIVO III',                     usuario: 'RCALITO' },
  { gafete: 23547, nombre: 'WILLIAM AUGUSTO VELÁSQUEZ FUENTES',           puesto: 'ANALISTA III',                               usuario: 'WAVELASQUEZ' },
  { gafete: 24421, nombre: 'SILVIA CAROLINA GONZÁLEZ CASTRO',             puesto: 'ANALISTA III',                               usuario: 'SCGONZALEZ' },
  { gafete: 25470, nombre: 'CLAUDIA TERESA SÁNCHEZ LEMUS',                puesto: 'AUDITOR INTERNO',                            usuario: 'CTSANCHEZ' },
  { gafete: 26480, nombre: 'MIGUEL ÁNGEL AMADO ORELLANA',                 puesto: 'PILOTO I',                                   usuario: 'MAMADO' },
  { gafete: 17291, nombre: 'ROSARIO ESPERANZA ESCOBAR GARCÍA',            puesto: 'ANALISTA III',                               usuario: 'ROESCOBAR' },
  { gafete: 31580, nombre: 'JOHANNA EILEEN ORDOÑEZ YOC',                  puesto: 'ANALISTA III',                               usuario: 'JEORDONEZ' },
  { gafete: 10626, nombre: 'DELMAR JUAN GONZÁLEZ SANTIZO',                puesto: 'SUPERVISOR DE AUDITORÍA',                    usuario: 'DGONZALEZ' },
  { gafete: 16004, nombre: 'SAMARA JUDITH MENA LÓPEZ',                    puesto: 'ANALISTA III',                               usuario: 'SJMENA' },
  { gafete: 21128, nombre: 'HENRY ARMANDO SÁNCHEZ ALEMÁN',                puesto: 'PILOTO II',                                  usuario: 'HASANCHEZ' },
  { gafete: 27892, nombre: 'CRISTÓBAL RAMÍREZ TINAY',                     puesto: 'ANALISTA III',                               usuario: 'CCRAMIREZ' },
  { gafete: 29158, nombre: 'ROBERTO VALLADARES CEREZO',                   puesto: 'ANALISTA III',                               usuario: 'RVALLADARES' },
  { gafete: 30114, nombre: 'YONI NEHEMÍAS PÉREZ CUYUCH',                  puesto: 'AUXILIAR DE SERVICIO I',                     usuario: 'YNPEREZ' },
  { gafete: 17292, nombre: 'HUGO FRANCISCO JAIR ESTRADA CASASOLA',        puesto: 'ANALISTA III',                               usuario: 'HESTRADA' },
  { gafete: 23689, nombre: 'LESLY ELISA FLORES COLINDRES',               puesto: 'ANALISTA III',                               usuario: 'LEFLORES' },
  { gafete: 26788, nombre: 'ANA LUCÍA MARROQUÍN TZUM',                    puesto: 'AUXILIAR OPERATIVO III',                     usuario: 'ALMARROQUINT' },
  { gafete: 26985, nombre: 'MARIO FERNANDO ESTRADA DEL CID',              puesto: 'ANALISTA III',                               usuario: 'MFESTRADA' },
  { gafete: 27054, nombre: 'YOVANY AUDI MÉNDEZ RODRÍGUEZ',                puesto: 'ANALISTA III',                               usuario: 'YMENDEZ' },
  { gafete: 27557, nombre: 'JOSEPH ALBERTH EMMANUEL AJCAN BARRIENTOS',    puesto: 'SUPERVISOR DE AUDITORÍA',                    usuario: 'JAJCAN' },
  { gafete: 28420, nombre: 'PATRICIA ELIZABETH VELÁSQUEZ CASTAÑÓN',       puesto: 'OFICINISTA III',                             usuario: 'PEVELASQUEZ' },
  { gafete: 29275, nombre: 'CARLOS RAFAEL TERCERO MUXÍ',                  puesto: 'ANALISTA III',                               usuario: 'CTERCERO' },
  { gafete: 15802, nombre: 'ROSA ODILIA NAVASSI DÍAZ',                    puesto: 'SUPERVISOR DE AUDITORÍA',                    usuario: 'RNAVASSI' },
  { gafete: 18918, nombre: 'DAVID DE PAZ MARCHORRO',                      puesto: 'ANALISTA III',                               usuario: 'DDEPAZM' },
  { gafete: 25440, nombre: 'EDWIN ADOLFO SERRANO LEMUS',                  puesto: 'PILOTO I',                                   usuario: 'ESERRANO' },
  { gafete: 25341, nombre: 'JOSÉ ÁNGEL REYES MORALES',                    puesto: 'ANALISTA III',                               usuario: 'JAREYES' },
  { gafete: 27066, nombre: 'CARLOS HUMBERTO HERNANDEZ SILVA',             puesto: 'PILOTO I',                                   usuario: 'CHHERNANDEZ' },
  { gafete: 31623, nombre: 'JOSE ANTONIO MIRANDA CORZO',                  puesto: 'CONSERJE-MENSAJERO',                         usuario: 'JAMIRANDA' }
];


exports.pools = {
  JAJCAN: ['DPALMA', 'WAVELASQUEZ', 'MFESTRADA', 'JAJCAN'],
  ALMARROQUINT: [
    'RCALITO', 'MAMADO', 'HASANCHEZ', 'ESERRANO',
    'PEVELASQUEZ', 'MDVELASQUEZ', 'RSRODRIGUEZ', 'YNPEREZ',
    'ALMARROQUINT', 'CHHERNANDEZ', 'JAMIRANDA'
  ],
  RNAVASSI: [
    'ROESCOBAR', 'CTERCERO', 'ECALVILLO', 'ABFRANCO',
    'SANZOATEGUI', 'RNAVASSI', 'RVALLADARES', 'HESTRADA'
  ],
  RRLOPEZ: [
    'JEORDONEZ', 'SCGONZALEZ', 'OBERMUDEZ', 'RRLOPEZ', 'LEFLORES'
  ],
  WFLOPEZ: [
    'WBAILON', 'SMOROZCOM', 'SJMENA', 'JAREYES',
    'DDEPAZM', 'WFLOPEZ', 'CCRAMIREZ', 'YMENDEZ'
  ],
   CTSANCHEZ: exports.infoEmpleados.map(e => e.usuario.toUpperCase())
};