exports.usuariosGafete = {
  PEVELASQUEZ: "28420",
  CTERCERO: "29275",
  ESERRANO: "25440",
  JAREYES: "25341",
  CCRAMIREZ: "27892",
  RVALLADARES: "29158",
  YNPEREZ: "30114",
  HESTRADA: "17292",
  LEFLORES: "23689",
  ALMARROQUINT: "26788",
  MFESTRADA: "26985",
  YMENDEZ: "27054",
  JAJCAN: "27557",
  DPALMA: "17357",
  WBAILON: "25488",
  SMOROZCOM: "28173",
  RCALITO: "17186",
  HASANCHEZ: "21128",
  WAVELASQUEZ: "23547",
  SCGONZALEZ: "24421",
  CTSANCHEZ: "25470",
  MAMADO: "26480",
  ROESCOBAR: "17291",
  JEORDONEZ: "31580",
  DGONZALEZ: "10626",
  SJMENA: "16004",
  RNAVASSI: "15802",
  DDEPAZM: "18918",
  MDVELASQUEZ: "28365",
  EQUICHE: "32601",
  RSRODRIGUEZ: "32832",
  OBERMUDEZ: "14443",
  EPORRAS: "15801",
  RRLOPEZ: "16560",
  WFLOPEZ: "18578",
  ECALVILLO: "21143",
  ABFRANCO: "21261",
  SANZOATEGUI: "28344",
  CHHERNANDEZ: "27066",
  JAMIRANDA: "31623"
};

exports.infoEmpleados = [
  { gafete: 28344, nombre: 'SIONIS GABRIELA ANZOÁTEGUI SALAZAR',          puesto: 'ANALISTA III',                           usuario: 'SANZOATEGUI',    horarioEspecial: false },
  { gafete: 28365, nombre: 'MARICARMEN DEL ROSARIO VELÁSQUEZ',            puesto: 'SECRETARIA EJECUTIVA I',                usuario: 'MDVELASQUEZ',     horarioEspecial: false },
  { gafete: 32601, nombre: 'EDGAR ARNOLDO QUICHÉ CHIYAL',                 puesto: 'SUPERVISOR DE AUDITORÍA',               usuario: 'EQUICHE',         horarioEspecial: false },
  { gafete: 32832, nombre: 'REYNA SUSANA RODRÍGUEZ CRUZ',                 puesto: 'OFICINISTA I',                          usuario: 'RSRODRIGUEZ',     horarioEspecial: false },
  { gafete: 14443, nombre: 'OLGA MARINA BERMÚDEZ ARANA',                  puesto: 'SECRETARIA V',                          usuario: 'OBERMUDEZ',       horarioEspecial: false },
  { gafete: 15801, nombre: 'ERICK GIOVANNI PORRAS RUBIO',                 puesto: 'SUPERVISOR GENERAL DE AUDITORÍA INTERNA',usuario: 'EPORRAS',         horarioEspecial: false },
  { gafete: 16560, nombre: 'RÓMULO ROMILIO LÓPEZ SÁNCHEZ',                puesto: 'SUPERVISOR DE AUDITORÍA',               usuario: 'RRLOPEZ',         horarioEspecial: false },
  { gafete: 18578, nombre: 'WILSON NICOLÁS LÓPEZ FLORIÁN',                puesto: 'SUPERVISOR DE AUDITORÍA',               usuario: 'WFLOPEZ',         horarioEspecial: false },
  { gafete: 21143, nombre: 'ELISA AZUCENA CALVILLO VALDEZ',               puesto: 'AUXILIAR DE AUDITORÍA',                 usuario: 'ECALVILLO',       horarioEspecial: false },
  { gafete: 21261, nombre: 'ANDREA BEATRIZ FRANCO TRUJILLO',              puesto: 'ANALISTA III',                          usuario: 'ABFRANCO',        horarioEspecial: false },
  { gafete: 17357, nombre: 'DENNIS FERNANDO PALMA RAMÍREZ',               puesto: 'ANALISTA III',                          usuario: 'DPALMA',          horarioEspecial: false },
  { gafete: 25488, nombre: 'WILSON OTTONIEL BAILÓN LETONA',               puesto: 'ANALISTA III',                          usuario: 'WBAILON',         horarioEspecial: false },
  { gafete: 28173, nombre: 'SUSY MARÍA ELISA OROZCO MÉRIDA',              puesto: 'ANALISTA III',                          usuario: 'SMOROZCOM',       horarioEspecial: false },
  { gafete: 17186, nombre: 'REYNA LUZ CUEVAS CALITO',                     puesto: 'AUXILIAR OPERATIVO III',                usuario: 'RCALITO',         horarioEspecial: true },
  { gafete: 23547, nombre: 'WILLIAM AUGUSTO VELÁSQUEZ FUENTES',           puesto: 'ANALISTA III',                          usuario: 'WAVELASQUEZ',     horarioEspecial: false },
  { gafete: 24421, nombre: 'SILVIA CAROLINA GONZÁLEZ CASTRO',             puesto: 'ANALISTA III',                          usuario: 'SCGONZALEZ',      horarioEspecial: false },
  { gafete: 25470, nombre: 'CLAUDIA TERESA SÁNCHEZ LEMUS',                puesto: 'AUDITOR INTERNO',                       usuario: 'CTSANCHEZ',       horarioEspecial: false },
  { gafete: 26480, nombre: 'MIGUEL ÁNGEL AMADO ORELLANA',                 puesto: 'PILOTO I',                              usuario: 'MAMADO',          horarioEspecial: false },
  { gafete: 17291, nombre: 'ROSARIO ESPERANZA ESCOBAR GARCÍA',            puesto: 'ANALISTA III',                          usuario: 'ROESCOBAR',       horarioEspecial: false },
  { gafete: 31580, nombre: 'JOHANNA EILEEN ORDOÑEZ YOC',                  puesto: 'ANALISTA III',                          usuario: 'JEORDONEZ',       horarioEspecial: false },
  { gafete: 10626, nombre: 'DELMAR JUAN GONZÁLEZ SANTIZO',                puesto: 'SUPERVISOR DE AUDITORÍA',               usuario: 'DGONZALEZ',       horarioEspecial: false },
  { gafete: 16004, nombre: 'SAMARA JUDITH MENA LÓPEZ',                    puesto: 'ANALISTA III',                          usuario: 'SJMENA',          horarioEspecial: false },
  { gafete: 21128, nombre: 'HENRY ARMANDO SÁNCHEZ ALEMÁN',                puesto: 'PILOTO II',                             usuario: 'HASANCHEZ',       horarioEspecial: false },
  { gafete: 27892, nombre: 'CRISTÓBAL RAMÍREZ TINAY',                     puesto: 'ANALISTA III',                          usuario: 'CCRAMIREZ',       horarioEspecial: false },
  { gafete: 29158, nombre: 'ROBERTO VALLADARES CEREZO',                   puesto: 'ANALISTA III',                          usuario: 'RVALLADARES',     horarioEspecial: false },
  { gafete: 30114, nombre: 'YONI NEHEMÍAS PÉREZ CUYUCH',                  puesto: 'AUXILIAR DE SERVICIO I',                usuario: 'YNPEREZ',         horarioEspecial: false },
  { gafete: 17292, nombre: 'HUGO FRANCISCO JAIR ESTRADA CASASOLA',        puesto: 'ANALISTA III',                          usuario: 'HESTRADA',        horarioEspecial: false },
  { gafete: 23689, nombre: 'LESLY ELISA FLORES COLINDRES',               puesto: 'ANALISTA III',                          usuario: 'LEFLORES',        horarioEspecial: false },
  { gafete: 26788, nombre: 'ANA LUCÍA MARROQUÍN TZUM',                    puesto: 'AUXILIAR OPERATIVO III',                usuario: 'ALMARROQUINT',    horarioEspecial: false },
  { gafete: 26985, nombre: 'MARIO FERNANDO ESTRADA DEL CID',              puesto: 'ANALISTA III',                          usuario: 'MFESTRADA',       horarioEspecial: false },
  { gafete: 27054, nombre: 'YOVANY AUDI MÉNDEZ RODRÍGUEZ',                puesto: 'ANALISTA III',                          usuario: 'YMENDEZ',         horarioEspecial: false },
  { gafete: 27557, nombre: 'JOSEPH ALBERTH EMMANUEL AJCAN BARRIENTOS',    puesto: 'SUPERVISOR DE AUDITORÍA',               usuario: 'JAJCAN',          horarioEspecial: false },
  { gafete: 28420, nombre: 'PATRICIA ELIZABETH VELÁSQUEZ CASTAÑÓN',       puesto: 'OFICINISTA III',                        usuario: 'PEVELASQUEZ',     horarioEspecial: false },
  { gafete: 29275, nombre: 'CARLOS RAFAEL TERCERO MUXÍ',                  puesto: 'ANALISTA III',                          usuario: 'CTERCERO',        horarioEspecial: false },
  { gafete: 15802, nombre: 'ROSA ODILIA NAVASSI DÍAZ',                    puesto: 'SUPERVISOR DE AUDITORÍA',               usuario: 'RNAVASSI',        horarioEspecial: false },
  { gafete: 18918, nombre: 'DAVID DE PAZ MARCHORRO',                      puesto: 'ANALISTA III',                          usuario: 'DDEPAZM',         horarioEspecial: false },
  { gafete: 25440, nombre: 'EDWIN ADOLFO SERRANO LEMUS',                  puesto: 'PILOTO I',                              usuario: 'ESERRANO',        horarioEspecial: false },
  { gafete: 25341, nombre: 'JOSÉ ÁNGEL REYES MORALES',                    puesto: 'ANALISTA III',                          usuario: 'JAREYES',         horarioEspecial: false },
  { gafete: 27066, nombre: 'CARLOS HUMBERTO HERNANDEZ SILVA',             puesto: 'PILOTO I',                              usuario: 'CHHERNANDEZ',     horarioEspecial: false },
  { gafete: 31623, nombre: 'JOSE ANTONIO MIRANDA CORZO',                  puesto: 'CONSERJE-MENSAJERO',                    usuario: 'JAMIRANDA',       horarioEspecial: true },
  { gafete: 33936, nombre: 'MELVIN WILFREDO ESTUPE MALDONADO',            puesto: 'SUPERVISOR DE AUDITORÍA',               usuario: 'MESTUPE',       horarioEspecial: false }
];



exports.pools = {
  JAJCAN: ['WAVELASQUEZ', 'MFESTRADA', 'JAJCAN'],
  ALMARROQUINT: [
    'RCALITO', 'MAMADO', 'HASANCHEZ', 'ESERRANO',
    'PEVELASQUEZ', 'MDVELASQUEZ', 'RSRODRIGUEZ', 'YNPEREZ',
    'ALMARROQUINT', 'CHHERNANDEZ', 'JAMIRANDA'
  ],
  MESTUPE: [
    'ROESCOBAR', 'CTERCERO', 'ECALVILLO', 'ABFRANCO',
    'SANZOATEGUI', 'RVALLADARES', 'HESTRADA'
  ],
  RRLOPEZ: [
    'JEORDONEZ', 'SCGONZALEZ', 'OBERMUDEZ', 'RRLOPEZ', 'LEFLORES'
  ],
  WFLOPEZ: [
    'WBAILON', 'SMOROZCOM', 'SJMENA', 'JAREYES',
    'DDEPAZM', 'WFLOPEZ', 'CCRAMIREZ', 'YMENDEZ'
  ],
  RNAVASSI: exports.infoEmpleados.map(e => e.usuario.toUpperCase()),
  CTSANCHEZ: exports.infoEmpleados.map(e => e.usuario.toUpperCase())
};